%% Test Without Hardware

uicontrol('Parent', tab_config, 'Style', 'text', ...
    'String', 'Test Without Hardware', ...
    'Units', 'normalized', ...
    'Position', [0.05 0.84 0.25 0.05], ...
    'FontSize', 15, ...
    'Tooltip','Offline mode for testing without being connected to hardware',...
    'FontWeight', 'bold');

bg_test = uibuttongroup('Parent', tab_config, ...
    'Units', 'normalized', ...
    'Position', [0.3 0.83 0.2 0.08], ...
    'SelectionChangedFcn', @(src, event) UpdateConfig('TestWithoutHardware', strcmp(event.NewValue.String, 'ON')));

uicontrol(bg_test, 'Style', 'radiobutton', ...
    'String', 'ON', ...
    'Units', 'normalized', ...
    'Position', [0.05 0.2 0.4 0.6], ...
    'Value', TestWithoutHardware == 1, ...
    'FontSize', 12);

uicontrol(bg_test, 'Style', 'radiobutton', ...
    'String', 'OFF', ...
    'Units', 'normalized', ...
    'Position', [0.55 0.2 0.4 0.6], ...
    'Value', TestWithoutHardware == 0, ...
    'FontSize', 12);

%% RF Address

uicontrol('Parent', tab_config, 'Style', 'text', ...
    'String', 'RF Address', ...
    'Units', 'normalized', ...
    'Position', [0.05 0.745 0.25 0.05], ...
    'FontSize', 15, ...
    'Tooltip','TCPIP or GPIB, see Connect_RF.m for troubleshooting',...
    'FontWeight', 'bold');

uicontrol('Parent', tab_config, 'Style', 'edit', ...
    'String', RF_Address, ...
    'Units', 'normalized', ...
    'Position', [0.25 0.75 0.3 0.06], ...
    'FontSize', 12, ...
    'Callback', @(src, ~) UpdateConfig('RF_Address', src.String), ...
    'TooltipString', 'Instrument communication address');

%% Data Path

uicontrol('Parent', tab_config, 'Style', 'text', ...
    'String', 'Data Path', ...
    'Units', 'normalized', ...
    'Position', [0.05 0.645 0.25 0.05], ...
    'FontSize', 15, ...
    'Tooltip','Path where the data will be saved',...
    'FontWeight', 'bold');

uicontrol('Parent', tab_config, 'Style', 'edit', ...
    'String', Data_Path, ...
    'Units', 'normalized', ...
    'Position', [0.25 0.65 0.45 0.06], ...
    'FontSize', 12, ...
    'tag', 'ConfigDataPath',...
    'Callback', @(src, ~) UpdateConfig('Data_Path', src.String), ...
    'TooltipString', 'Root directory for acquisition data');

uicontrol('Parent', tab_config, 'Style', 'pushbutton', ...
    'String', 'Browse', ...
    'Units', 'normalized', ...
    'Position', [0.72 0.65 0.1 0.06], ...
    'FontSize', 12, ...
    'Callback', @(~,~) BrowseDataPath(Data_Path), ...
    'TooltipString', 'Select folder');

%% Camera Choice

uicontrol('Parent', tab_config, 'Style', 'text', ...
    'String', 'Camera', ...
    'Units', 'normalized', ...
    'Position', [0.05 0.54 0.25 0.05], ...
    'FontSize', 15, ...
    'Tooltip','Choose wisely',...
    'FontWeight', 'bold');

cams = {'uEye', 'Peak', 'Andor', 'heliCam', 'Thorlabs'};

bg_cam = uibuttongroup('Parent', tab_config, ...
    'Units', 'normalized', ...
    'Position', [0.25 0.52 0.6 0.1], ...
    'SelectionChangedFcn', @(src, event) UpdateConfig('CameraChoice', event.NewValue.String));

for i = 1:numel(cams)
    uicontrol(bg_cam, 'Style', 'radiobutton', ...
        'String', cams{i}, ...
        'Units', 'normalized', ...
        'Position', [0.02 + (i-1)*0.19 0.2 0.18 0.6], ...
        'Value', strcmp(CameraChoice, cams{i}), ...
        'FontSize', 12);
end

%% Setup Type

uicontrol('Parent', tab_config, 'Style', 'text', ...
    'String', 'Setup Type', ...
    'Units', 'normalized', ...
    'Position', [0.05 0.41 0.25 0.05], ...
    'FontSize', 15, ...
    'Tooltip','To indicate if you use piezo XY, piezo Z, which kind of light etc, important for AutoAlignPiezo',...
    'FontWeight', 'bold');

setups = {'CEA', 'ENS1', 'BASE'};

bg_setup = uibuttongroup('Parent', tab_config, ...
    'Units', 'normalized', ...
    'Position', [0.25 0.39 0.4 0.1], ...
    'SelectionChangedFcn', @(src, event) UpdateConfig('SetupType', event.NewValue.String));

for i = 1:numel(setups)
    uicontrol(bg_setup, 'Style', 'radiobutton', ...
        'String', setups{i}, ...
        'Units', 'normalized', ...
        'Position', [0.1 + (i-1)*0.25 0.2 0.2 0.6], ...
        'Value', strcmp(setups{i}, SetupType), ...
        'FontSize', 12);
end

%% Restart Disclaimer

uicontrol('Parent', tab_config, 'Style', 'text', ...
    'String', 'Restart program to apply changes', ...
    'Units', 'normalized', ...
    'ForegroundColor', 'red', ...
    'Position', [0.3 0.29 0.25 0.05], ...
    'FontSize', 20, ...
    'FontWeight', 'bold');

uicontrol('Parent', tab_config, 'Style', 'text', ...
    'String', 'All these parameters can be set manually in the file config.txt in the Param folder.', ...
    'Units', 'normalized', ...
    'Position', [0.225 0.2 0.41 0.05], ...
    'FontSize', 15, ...
    'FontWeight', 'bold');




